# Generated by Django 4.2.30 on 2026-04-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
