# Generated by Django 4.2.30 on 2026-05-01 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendance_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='attendance_end_time',
            field=models.TimeField(default=datetime.time(11, 0), help_text='Attendance marking closes at this time'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='attendance_start_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Attendance marking opens at this time'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='late_cutoff_time',
            field=models.TimeField(default=datetime.time(9, 30), help_text='Attendance marked after this time (but before end) is flagged as late'),
        ),
    ]
