# Generated by Django 4.2.30 on 2026-05-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_changerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Change Request', 'verbose_name_plural': 'Change Requests'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Teacher Profile', 'verbose_name_plural': 'Teacher Profiles'},
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Admin response / reason'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='date_affected',
            field=models.DateField(blank=True, help_text='Relevant date if attendance change', null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='description',
            field=models.TextField(help_text='Describe exactly what needs to change'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='request_type',
            field=models.CharField(choices=[('attendance', 'Attendance Change'), ('student_info', 'Student Info Change'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='student_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
