# Generated by Django 5.2.13 on 2026-05-05 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_changerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 2022 for the 2022-26 batch', null=True),
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(help_text='e.g. Btech, BCA, BCS', max_length=50)),
                ('name', models.CharField(help_text='e.g. 2024-25', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one session per course should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'ordering': ['-start_date'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='PDF, image, or Excel file', null=True, upload_to='timetables/')),
                ('grid_data', models.JSONField(blank=True, help_text='Structured timetable data from the grid form', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional info for the teacher')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, help_text='Which session this timetable applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicsession')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='core.teacherprofile')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('session', models.ForeignKey(blank=True, help_text='Leave blank to apply to all sessions (national holidays)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.academicsession')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
                'unique_together': {('date', 'session')},
            },
        ),
    ]
