# Generated by Django 4.2.30 on 2026-05-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_session_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
